TITLE = "Double Gauss Lens"

SURFACES = [
    {
        "surface": "Object",
        "name": "Object",
        "rc": 0.0,
        "thickness": 120.0,
        "diameter": 20.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "name": "Front Crown Front",
        "rc": 55.0,
        "thickness": 7.0,
        "diameter": 34.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "name": "Front Crown Back",
        "rc": -90.0,
        "thickness": 4.0,
        "diameter": 32.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "name": "Front Flint Front",
        "rc": -38.0,
        "thickness": 3.0,
        "diameter": 28.0,
        "glass": "F2",
    },
    {
        "surface": "Standard",
        "name": "Front Flint Back",
        "rc": 70.0,
        "thickness": 18.0,
        "diameter": 26.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "name": "Rear Flint Front",
        "rc": -70.0,
        "thickness": 3.0,
        "diameter": 26.0,
        "glass": "F2",
    },
    {
        "surface": "Standard",
        "name": "Rear Flint Back",
        "rc": 38.0,
        "thickness": 4.0,
        "diameter": 28.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "name": "Rear Crown Front",
        "rc": 90.0,
        "thickness": 7.0,
        "diameter": 32.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "name": "Rear Crown Back",
        "rc": -55.0,
        "thickness": 70.0,
        "diameter": 34.0,
        "glass": "AIR",
    },
    {
        "surface": "Image",
        "name": "Image",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 12.0,
        "glass": "AIR",
    },
]
