TITLE = "Double Mirror Fold"

SURFACES = [
    {
        "surface": "Object",
        "name": "Object",
        "rc": 0.0,
        "thickness": 20.0,
        "diameter": 20.0,
        "tilt_x": 0.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "AIR",
    },
    {
        "surface": "Mirror",
        "name": "Mirror 1",
        "rc": 0.0,
        "thickness": 30.0,
        "diameter": 30.0,
        "tilt_x": 44.5,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "MIRROR",
    },
    {
        "surface": "Standard",
        "name": "Lens Front",
        "rc": 51.68,
        "thickness": 6.0,
        "diameter": 25.0,
        "tilt_x": 0.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "name": "Lens Back",
        "rc": -51.68,
        "thickness": 30.0,
        "diameter": 25.0,
        "tilt_x": 0.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "AIR",
    },
    {
        "surface": "Mirror",
        "name": "Mirror 2",
        "rc": 0.0,
        "thickness": 20.0,
        "diameter": 30.0,
        "tilt_x": -45.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "MIRROR",
    },
    {
        "surface": "Image",
        "name": "Image",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 20.0,
        "tilt_x": 0.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "AIR",
    },
]
